---

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker package
  package:
    name: "{{ docker_engine_package }}"
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: "yes"
