---

- name: Remove old versions of Docker if installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker repository.
  get_url:
    url: "{{ yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_engine_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure default docker storage-driver for RedHat.
  set_fact:
    docker_daemon_opts: "{{docker_daemon_opts|combine( {'storage-driver': '{{ docker_redhat_storage_driver }}' } )}}"
  when: "'storage-driver' not in docker_daemon_opts"
